/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MemosSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  memosServerUrl: "",
  memosAccessToken: "",
  autoSync: false,
  syncIntervalMinutes: 30,
  dailyNotesFolder: "DailyNotes",
  fileNameFormat: "YYYY-MM-DD",
  memosHeading: "## Memos",
  insertPosition: "bottom",
  memoTemplate: "- \u23F0 {{time}} | {{content}}",
  dateTimeFormat: "HH:mm",
  tagPrefix: "#",
  filterTag: "",
  syncLimit: 100,
  syncLookbackDays: 3,
  syncOnStartup: "off",
  syncOnFileOpen: false
};
var MemosSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Memos server configuration").setHeading();
    new import_obsidian.Setting(containerEl).setName("Memos server URL").setDesc(
      "The base URL of your Memos instance (e.g., https://memos.example.com)"
    ).addText(
      (text) => text.setPlaceholder("https://memos.example.com").setValue(this.plugin.settings.memosServerUrl).onChange(async (value) => {
        this.plugin.settings.memosServerUrl = value.trim().replace(/\/+$/, "");
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Access token").setDesc("Your Memos API access token for authentication").addText(
      (text) => text.setPlaceholder("Enter your access token").setValue(this.plugin.settings.memosAccessToken).onChange(async (value) => {
        this.plugin.settings.memosAccessToken = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync options").setHeading();
    new import_obsidian.Setting(containerEl).setName("Auto sync").setDesc("Automatically sync memos at a regular interval").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
        this.plugin.settings.autoSync = value;
        await this.plugin.saveSettings();
        this.plugin.resetAutoSync();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync interval (minutes)").setDesc("How often to auto-sync memos (in minutes)").addText(
      (text) => text.setPlaceholder("30").setValue(String(this.plugin.settings.syncIntervalMinutes)).onChange(async (value) => {
        const parsed = parseInt(value, 10);
        if (!isNaN(parsed) && parsed >= 1) {
          this.plugin.settings.syncIntervalMinutes = parsed;
          await this.plugin.saveSettings();
          this.plugin.resetAutoSync();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync limit").setDesc("Maximum number of memos to fetch per sync").addText(
      (text) => text.setPlaceholder("100").setValue(String(this.plugin.settings.syncLimit)).onChange(async (value) => {
        const parsed = parseInt(value, 10);
        if (!isNaN(parsed) && parsed >= 1) {
          this.plugin.settings.syncLimit = parsed;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("File and folder paths").setHeading();
    new import_obsidian.Setting(containerEl).setName("Daily notes folder").setDesc("Folder where daily notes are stored").addText(
      (text) => text.setPlaceholder("DailyNotes").setValue(this.plugin.settings.dailyNotesFolder).onChange(async (value) => {
        this.plugin.settings.dailyNotesFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("File name format").setDesc(
      "Date format for daily note file names (e.g., YYYY-MM-DD, YYYY/MM/YYYY-MM-DD)"
    ).addText(
      (text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.fileNameFormat).onChange(async (value) => {
        this.plugin.settings.fileNameFormat = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Content formatting").setHeading();
    new import_obsidian.Setting(containerEl).setName("Memos section heading").setDesc("The heading text for the memos section in your daily note").addText(
      (text) => text.setPlaceholder("## Memos").setValue(this.plugin.settings.memosHeading).onChange(async (value) => {
        this.plugin.settings.memosHeading = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Insert position").setDesc("Where to insert the memos section in the daily note").addDropdown(
      (dropdown) => dropdown.addOption("bottom", "Bottom of file").addOption("top", "Top of file").setValue(this.plugin.settings.insertPosition).onChange(async (value) => {
        this.plugin.settings.insertPosition = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Memo template").setDesc(
      "Template for each memo. Placeholders: {{time}}, {{content}}, {{tags}}, {{uid}}"
    ).addTextArea(
      (text) => text.setPlaceholder("- \u23F0 {{time}} | {{content}}").setValue(this.plugin.settings.memoTemplate).onChange(async (value) => {
        this.plugin.settings.memoTemplate = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Time format").setDesc("Format for memo timestamps (e.g., HH:mm, HH:mm:ss)").addText(
      (text) => text.setPlaceholder("HH:mm").setValue(this.plugin.settings.dateTimeFormat).onChange(async (value) => {
        this.plugin.settings.dateTimeFormat = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Tag prefix").setDesc("Prefix for tags in memos (e.g., # or #memos/)").addText(
      (text) => text.setPlaceholder("#").setValue(this.plugin.settings.tagPrefix).onChange(async (value) => {
        this.plugin.settings.tagPrefix = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto triggers").setHeading();
    new import_obsidian.Setting(containerEl).setName("Sync on startup").setDesc(
      "Automatically sync once after Obsidian starts. Changes take effect on next launch."
    ).addDropdown(
      (dropdown) => dropdown.addOption("off", "Off").addOption("1", "After 1 second").addOption("10", "After 10 seconds").addOption("30", "After 30 seconds").setValue(this.plugin.settings.syncOnStartup).onChange(async (value) => {
        this.plugin.settings.syncOnStartup = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync on daily note open").setDesc(
      "When you open a daily note within the lookback range, automatically sync the latest memos for that date."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.syncOnFileOpen).onChange(async (value) => {
        this.plugin.settings.syncOnFileOpen = value;
        await this.plugin.saveSettings();
        this.plugin.resetFileOpenSync();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Filter").setHeading();
    new import_obsidian.Setting(containerEl).setName("Sync lookback days").setDesc(
      "How many past days to sync in addition to today (0 = today only, 3 = today + past 3 days). Useful for catching edits to older memos."
    ).addText(
      (text) => text.setPlaceholder("3").setValue(String(this.plugin.settings.syncLookbackDays)).onChange(async (value) => {
        const parsed = parseInt(value, 10);
        if (!isNaN(parsed) && parsed >= 0 && parsed <= 30) {
          this.plugin.settings.syncLookbackDays = parsed;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Filter by tag").setDesc("Only sync memos that contain this tag (leave empty to sync all)").addText(
      (text) => text.setPlaceholder("").setValue(this.plugin.settings.filterTag).onChange(async (value) => {
        this.plugin.settings.filterTag = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Actions").setHeading();
    new import_obsidian.Setting(containerEl).setName("Test connection").setDesc("Test the connection to your Memos server").addButton(
      (button) => button.setButtonText("Test").onClick(async () => {
        button.setButtonText("Testing...");
        button.setDisabled(true);
        try {
          const result = await this.plugin.memosApi.testConnectionDetailed();
          if (result.ok) {
            new import_obsidian.Notice(`\u2705 ${result.message}`);
          } else {
            new import_obsidian.Notice(`\u274C ${result.message}`, 1e4);
          }
        } catch (e) {
          new import_obsidian.Notice("\u274C Unexpected error: " + e.message, 1e4);
        } finally {
          button.setButtonText("Test");
          button.setDisabled(false);
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync now").setDesc("Manually trigger a sync right now").addButton(
      (button) => button.setButtonText("Sync Now").onClick(async () => {
        await this.plugin.syncMemos();
      })
    );
  }
};

// src/api.ts
var import_obsidian2 = require("obsidian");
var MemosApi = class {
  constructor(settings) {
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  get baseUrl() {
    return this.settings.memosServerUrl.replace(/\/+$/, "");
  }
  get headers() {
    const h = {
      "Content-Type": "application/json"
    };
    if (this.settings.memosAccessToken) {
      h["Authorization"] = `Bearer ${this.settings.memosAccessToken}`;
    }
    return h;
  }
  /**
   * Safe request wrapper.
   * Obsidian's requestUrl throws on non-2xx status codes,
   * so we catch those and extract the status from the error.
   */
  async safeRequest(url, method = "GET", includeAuth = true) {
    try {
      const params = {
        url,
        method,
        headers: includeAuth ? this.headers : { "Content-Type": "application/json" }
      };
      const resp = await (0, import_obsidian2.requestUrl)(params);
      let body = null;
      try {
        body = resp.json;
      } catch (e) {
        body = resp.text;
      }
      return { status: resp.status, body };
    } catch (e) {
      const errorObj = e;
      const status = this.extractStatusFromError(errorObj);
      const errorMsg = (errorObj == null ? void 0 : errorObj.message) || String(e);
      console.debug(`Memos Sync: Request to ${url} failed - status: ${status}, error: ${errorMsg}`);
      return { status, body: null, error: errorMsg };
    }
  }
  /**
   * Try to extract HTTP status code from Obsidian requestUrl error
   */
  extractStatusFromError(e) {
    if (e == null ? void 0 : e.status)
      return e.status;
    const msg = (e == null ? void 0 : e.message) || "";
    const match = msg.match(/\b(4\d{2}|5\d{2})\b/);
    if (match)
      return parseInt(match[1], 10);
    return 0;
  }
  /**
   * Test connection to the Memos server.
   * Throws an Error with a descriptive message on failure.
   * Returns true on success.
   */
  async testConnection() {
    const result = await this.testConnectionDetailed();
    if (!result.ok) {
      throw new Error(result.message);
    }
    return true;
  }
  /**
   * Detailed connection test for latest Memos (v0.22+).
   *
   * Step 1: Hit /api/v1/workspace/profile (no auth) to verify server is reachable
   * Step 2: Hit /api/v1/memos?pageSize=1 (with auth) to verify token works
   */
  async testConnectionDetailed() {
    if (!this.settings.memosServerUrl) {
      return { ok: false, message: "Server URL is not configured." };
    }
    if (!this.settings.memosAccessToken) {
      return { ok: false, message: "Access token is not configured." };
    }
    const profileUrl = `${this.baseUrl}/api/v1/workspace/profile`;
    console.debug(`Memos Sync: Testing server reachability at ${profileUrl}`);
    const profileResult = await this.safeRequest(profileUrl, "GET", false);
    if (profileResult.status === 0) {
      return {
        ok: false,
        message: `Cannot reach server at ${this.baseUrl}.

Possible causes:
\u2022 The server URL is incorrect
\u2022 The server is not running
\u2022 Network/firewall/CORS issues

Error: ${profileResult.error || "Network error"}`
      };
    }
    if (profileResult.status === 404) {
      const fallbackUrl = `${this.baseUrl}/api/v1/memos?pageSize=1`;
      console.debug(`Memos Sync: Profile endpoint not found, trying ${fallbackUrl}`);
      const fallbackResult = await this.safeRequest(fallbackUrl, "GET", true);
      if (fallbackResult.status === 200) {
        return {
          ok: true,
          message: "Connected successfully! (workspace/profile not available, but memos API works)",
          version: "unknown"
        };
      }
      if (fallbackResult.status === 401 || fallbackResult.status === 403) {
        return {
          ok: false,
          message: `Server found but authentication failed (HTTP ${fallbackResult.status}).

Please check your access token:
\u2022 Go to Memos \u2192 Settings \u2192 Access Tokens
\u2022 Create a new token and paste it in the plugin settings`
        };
      }
      return {
        ok: false,
        message: `Server at ${this.baseUrl} does not appear to be a Memos instance.

/api/v1/workspace/profile returned HTTP ${profileResult.status}
/api/v1/memos returned HTTP ${fallbackResult.status || "no response"}

Please verify the URL is correct.`
      };
    }
    let version = "unknown";
    if (profileResult.status === 200 && profileResult.body) {
      const profileBody = profileResult.body;
      version = (profileBody == null ? void 0 : profileBody.version) || "unknown";
      console.debug(`Memos Sync: Server version detected: ${version}`);
    }
    const memosUrl = `${this.baseUrl}/api/v1/memos?pageSize=1`;
    console.debug(`Memos Sync: Testing authentication at ${memosUrl}`);
    const memosResult = await this.safeRequest(memosUrl, "GET", true);
    if (memosResult.status === 200) {
      const versionDisplay = version !== "unknown" ? ` (version: ${version})` : "";
      return {
        ok: true,
        message: `Connected successfully!${versionDisplay}`,
        version
      };
    }
    if (memosResult.status === 401 || memosResult.status === 403) {
      return {
        ok: false,
        message: `Server is reachable but authentication failed (HTTP ${memosResult.status}).

Please check your access token:
\u2022 Go to Memos \u2192 Settings \u2192 Access Tokens
\u2022 Create a new token and paste it in the plugin settings
\u2022 Make sure you're using the token value, not the token name`
      };
    }
    return {
      ok: false,
      message: `Server is reachable${version !== "unknown" ? ` (version: ${version})` : ""} but memos API returned HTTP ${memosResult.status}.

Error: ${memosResult.error || "Unknown error"}

Please check your Memos version is v0.22+ and the token has proper permissions.`
    };
  }
  /**
   * Fetch memos for a specific date (YYYY-MM-DD)
   * For latest Memos v0.22+, we fetch all memos and filter by date client-side,
   * because the filter CEL syntax for time ranges can vary between versions.
   */
  async fetchMemosByDate(dateStr) {
    const startOfDay = new Date(`${dateStr}T00:00:00`);
    const nextDay = this.getNextDay(dateStr);
    const endOfDay = new Date(`${nextDay}T00:00:00`);
    let allMemos = [];
    let pageToken = "";
    const pageSize = Math.min(this.settings.syncLimit, 50);
    do {
      let url = `${this.baseUrl}/api/v1/memos?pageSize=${pageSize}`;
      if (pageToken) {
        url += `&pageToken=${encodeURIComponent(pageToken)}`;
      }
      console.debug(`Memos Sync: Fetching memos from ${url}`);
      const result = await this.safeRequest(url);
      if (result.status === 401 || result.status === 403) {
        throw new Error(
          `Authentication failed (HTTP ${result.status}). Please check your access token.`
        );
      }
      if (result.status !== 200) {
        throw new Error(
          `Failed to fetch memos: HTTP ${result.status}${result.error ? " - " + result.error : ""}`
        );
      }
      const data = result.body;
      if (!data) {
        throw new Error("Empty response from Memos API");
      }
      const memos = (data.memos || []).map(
        (m) => this.parseMemo(m)
      );
      for (const memo of memos) {
        const memoTime = new Date(memo.displayTime || memo.createTime);
        if (memoTime >= startOfDay && memoTime < endOfDay) {
          allMemos.push(memo);
        }
      }
      pageToken = data.nextPageToken || "";
      if (memos.length > 0) {
        const oldestMemo = memos[memos.length - 1];
        const oldestTime = new Date(oldestMemo.displayTime || oldestMemo.createTime);
        if (oldestTime < startOfDay) {
          break;
        }
      }
      if (allMemos.length >= this.settings.syncLimit) {
        allMemos = allMemos.slice(0, this.settings.syncLimit);
        break;
      }
    } while (pageToken);
    if (this.settings.filterTag) {
      allMemos = allMemos.filter(
        (m) => m.tags.some((t) => t === this.settings.filterTag)
      );
    }
    allMemos.sort(
      (a, b) => new Date(a.displayTime).getTime() - new Date(b.displayTime).getTime()
    );
    return allMemos;
  }
  parseMemo(raw) {
    return {
      uid: raw.uid || raw.name || "",
      name: raw.name || "",
      content: raw.content || "",
      createTime: raw.createTime || "",
      updateTime: raw.updateTime || "",
      displayTime: raw.displayTime || raw.createTime || "",
      tags: raw.tags || [],
      pinned: raw.pinned || false,
      resources: (raw.resources || []).map((r) => ({
        name: r.name || "",
        filename: r.filename || "",
        externalLink: r.externalLink || "",
        type: r.type || "",
        size: r.size || "0"
      }))
    };
  }
  getNextDay(dateStr) {
    const d = new Date(dateStr + "T00:00:00Z");
    d.setUTCDate(d.getUTCDate() + 1);
    const yyyy = d.getUTCFullYear();
    const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
    const dd = String(d.getUTCDate()).padStart(2, "0");
    return `${yyyy}-${mm}-${dd}`;
  }
};

// src/utils.ts
function formatDate(date, pattern) {
  const tokens = {
    YYYY: String(date.getFullYear()),
    MM: String(date.getMonth() + 1).padStart(2, "0"),
    DD: String(date.getDate()).padStart(2, "0"),
    HH: String(date.getHours()).padStart(2, "0"),
    mm: String(date.getMinutes()).padStart(2, "0"),
    ss: String(date.getSeconds()).padStart(2, "0")
  };
  let result = pattern;
  for (const [token, value] of Object.entries(tokens)) {
    result = result.replace(new RegExp(token, "g"), value);
  }
  return result;
}
function getDailyNotePath(date, settings) {
  const folder = settings.dailyNotesFolder.replace(/^\/+|\/+$/g, "");
  const fileName = formatDate(date, settings.fileNameFormat);
  if (folder) {
    return `${folder}/${fileName}.md`;
  }
  return `${fileName}.md`;
}
var MEMO_UID_PREFIX = '<span class="memo-uid" data-uid="';
var MEMO_UID_SUFFIX = '"></span>';
var LEGACY_PREFIXES = ["%% memo-uid:", "<!-- memo-uid:"];
var LEGACY_SUFFIXES = [" %%", " -->"];
function buildUidMarker(uid) {
  return `${MEMO_UID_PREFIX}${uid}${MEMO_UID_SUFFIX}`;
}
function extractUidFromLine(line) {
  const idx = line.indexOf(MEMO_UID_PREFIX);
  if (idx !== -1) {
    const start = idx + MEMO_UID_PREFIX.length;
    const end = line.indexOf(MEMO_UID_SUFFIX, start);
    if (end !== -1)
      return line.substring(start, end).trim();
  }
  for (let i = 0; i < LEGACY_PREFIXES.length; i++) {
    const legIdx = line.indexOf(LEGACY_PREFIXES[i]);
    if (legIdx !== -1) {
      const legStart = legIdx + LEGACY_PREFIXES[i].length;
      const legEnd = line.indexOf(LEGACY_SUFFIXES[i], legStart);
      if (legEnd !== -1)
        return line.substring(legStart, legEnd).trim();
    }
  }
  return null;
}
function formatMemo(memo, settings) {
  const displayDate = new Date(memo.displayTime);
  const timeStr = formatDate(displayDate, settings.dateTimeFormat);
  const tagsStr = memo.tags.map((t) => `${settings.tagPrefix}${t}`).join(" ");
  const content = memo.content.trim();
  let result = settings.memoTemplate;
  result = result.replace(/\{\{time\}\}/g, timeStr);
  result = result.replace(/\{\{content\}\}/g, content);
  result = result.replace(/\{\{tags\}\}/g, tagsStr);
  result = result.replace(/\{\{uid\}\}/g, memo.uid);
  const uidMarker = buildUidMarker(memo.uid);
  const lines = result.split("\n");
  const listMatch = lines[0].match(/^(\s*[-*+]\s)/);
  if (listMatch) {
    lines[0] = listMatch[1] + uidMarker + lines[0].slice(listMatch[1].length);
  } else {
    lines[0] = uidMarker + lines[0];
  }
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() !== "" && !lines[i].startsWith("  ") && !lines[i].startsWith("	")) {
      lines[i] = "  " + lines[i];
    }
  }
  result = lines.join("\n");
  return result;
}
function isStandaloneUidMarkerLine(line) {
  const trimmed = line.trim();
  if (trimmed.startsWith("%% memo-uid:") && trimmed.endsWith(" %%")) {
    return trimmed.slice("%% memo-uid:".length, -" %%".length).trim();
  }
  if (trimmed.startsWith("<!-- memo-uid:") && trimmed.endsWith("-->")) {
    let inner = trimmed.slice("<!-- memo-uid:".length, -"-->".length).trim();
    inner = inner.replace(/[\s-]+$/, "");
    return inner || null;
  }
  return null;
}
function parseSectionBlocks(sectionLines) {
  const blocks = [];
  const memoStartUid = /* @__PURE__ */ new Map();
  const uidMarkerLineIndices = /* @__PURE__ */ new Set();
  for (let i = 0; i < sectionLines.length; i++) {
    const line = sectionLines[i];
    const inlineUid = extractUidFromLine(line);
    if (inlineUid) {
      const standaloneUid = isStandaloneUidMarkerLine(line);
      if (standaloneUid) {
        uidMarkerLineIndices.add(i);
        let contentIdx = i - 1;
        while (contentIdx >= 0 && sectionLines[contentIdx].trim() === "") {
          contentIdx--;
        }
        if (contentIdx >= 0 && !memoStartUid.has(contentIdx) && !uidMarkerLineIndices.has(contentIdx)) {
          memoStartUid.set(contentIdx, standaloneUid);
        }
      } else {
        memoStartUid.set(i, inlineUid);
      }
    }
  }
  let currentBlock = null;
  for (let i = 0; i < sectionLines.length; i++) {
    const line = sectionLines[i];
    if (memoStartUid.has(i)) {
      if (currentBlock)
        blocks.push(currentBlock);
      currentBlock = { type: "memo", uid: memoStartUid.get(i), lines: [line] };
    } else if (uidMarkerLineIndices.has(i)) {
      if (currentBlock && currentBlock.type === "memo") {
        currentBlock.lines.push(line);
      }
    } else if (currentBlock && currentBlock.type === "memo") {
      const isContinuation = line.startsWith("  ") || line.startsWith("	") || line.trim() === "";
      if (isContinuation) {
        currentBlock.lines.push(line);
      } else {
        blocks.push(currentBlock);
        currentBlock = { type: "manual", lines: [line] };
      }
    } else {
      if (!currentBlock || currentBlock.type !== "manual") {
        if (currentBlock)
          blocks.push(currentBlock);
        currentBlock = { type: "manual", lines: [line] };
      } else {
        currentBlock.lines.push(line);
      }
    }
  }
  if (currentBlock)
    blocks.push(currentBlock);
  return blocks;
}
function buildMemosSection(memos, settings) {
  const heading = settings.memosHeading;
  const items = memos.map((m) => formatMemo(m, settings));
  const lines = [heading, "", ...items, ""];
  return lines.join("\n");
}
function mergeMemosIntoNote(existingContent, memosSection, settings) {
  var _a, _b;
  const heading = settings.memosHeading.trim();
  const headingLevel = (heading.match(/^#+/) || ["##"])[0];
  const headingRegex = new RegExp(
    `^${escapeRegExp(heading)}\\s*$`,
    "m"
  );
  if (headingRegex.test(existingContent)) {
    const lines = existingContent.split("\n");
    let sectionStart = -1;
    let sectionEnd = lines.length;
    for (let i = 0; i < lines.length; i++) {
      if (headingRegex.test(lines[i].trim())) {
        sectionStart = i;
        continue;
      }
      if (sectionStart >= 0 && i > sectionStart) {
        const match = lines[i].match(/^(#+)\s/);
        if (match && match[1].length <= headingLevel.length) {
          sectionEnd = i;
          break;
        }
      }
    }
    if (sectionStart >= 0) {
      const before = lines.slice(0, sectionStart);
      const after = lines.slice(sectionEnd);
      let bodyStart = sectionStart + 1;
      while (bodyStart < sectionEnd && lines[bodyStart].trim() === "") {
        bodyStart++;
      }
      const existingSectionBody = lines.slice(bodyStart, sectionEnd);
      const newMemosLines = memosSection.split("\n");
      let newBodyStart = 0;
      for (let i = 0; i < newMemosLines.length; i++) {
        if (headingRegex.test(newMemosLines[i].trim())) {
          newBodyStart = i + 1;
          break;
        }
      }
      while (newBodyStart < newMemosLines.length && newMemosLines[newBodyStart].trim() === "") {
        newBodyStart++;
      }
      let newBodyEnd = newMemosLines.length;
      while (newBodyEnd > newBodyStart && newMemosLines[newBodyEnd - 1].trim() === "") {
        newBodyEnd--;
      }
      const newMemosBody = newMemosLines.slice(newBodyStart, newBodyEnd);
      const existingBlocks = parseSectionBlocks(existingSectionBody);
      const newBlocks = parseSectionBlocks(newMemosBody);
      console.debug(`Memos Sync: [merge] existingSectionBody lines: ${existingSectionBody.length}`);
      for (const b of existingBlocks) {
        console.debug(`Memos Sync: [merge] existing block: type=${b.type}, uid=${b.uid || "N/A"}, lines=${b.lines.length}, firstLine="${(_a = b.lines[0]) == null ? void 0 : _a.substring(0, 80)}"`);
      }
      console.debug(`Memos Sync: [merge] newMemosBody lines: ${newMemosBody.length}`);
      for (const b of newBlocks) {
        console.debug(`Memos Sync: [merge] new block: type=${b.type}, uid=${b.uid || "N/A"}, lines=${b.lines.length}, firstLine="${(_b = b.lines[0]) == null ? void 0 : _b.substring(0, 80)}"`);
      }
      const newMemoMap = /* @__PURE__ */ new Map();
      const newMemoOrder = [];
      for (const block of newBlocks) {
        if (block.type === "memo" && block.uid) {
          newMemoMap.set(block.uid, block);
          newMemoOrder.push(block.uid);
        }
      }
      const existingMemoUids = /* @__PURE__ */ new Set();
      for (const block of existingBlocks) {
        if (block.type === "memo" && block.uid) {
          existingMemoUids.add(block.uid);
        }
      }
      const newUids = newMemoOrder.filter((uid) => !existingMemoUids.has(uid));
      console.debug(`Memos Sync: [merge] existingMemoUids: [${[...existingMemoUids].join(", ")}]`);
      console.debug(`Memos Sync: [merge] newMemoOrder (from API): [${newMemoOrder.join(", ")}]`);
      console.debug(`Memos Sync: [merge] newUids (to insert): [${newUids.join(", ")}]`);
      const insertBeforeMap = /* @__PURE__ */ new Map();
      const appendAtEnd = [];
      for (const newUid of newUids) {
        const newIdx = newMemoOrder.indexOf(newUid);
        let placed = false;
        for (let j = newIdx + 1; j < newMemoOrder.length; j++) {
          const nextUid = newMemoOrder[j];
          if (existingMemoUids.has(nextUid)) {
            if (!insertBeforeMap.has(nextUid)) {
              insertBeforeMap.set(nextUid, []);
            }
            insertBeforeMap.get(nextUid).push(newUid);
            placed = true;
            break;
          }
        }
        if (!placed) {
          appendAtEnd.push(newUid);
        }
      }
      const mergedLines = [];
      for (const block of existingBlocks) {
        if (block.type === "memo" && block.uid) {
          const toInsertBefore = insertBeforeMap.get(block.uid);
          if (toInsertBefore) {
            for (const uid of toInsertBefore) {
              const newBlock = newMemoMap.get(uid);
              if (newBlock)
                mergedLines.push(...newBlock.lines);
            }
          }
          if (newMemoMap.has(block.uid)) {
            const updated = newMemoMap.get(block.uid);
            const oldTrimmedLines = block.lines.slice();
            while (oldTrimmedLines.length > 0 && oldTrimmedLines[oldTrimmedLines.length - 1].trim() === "") {
              oldTrimmedLines.pop();
            }
            const newTrimmedLines = updated.lines.slice();
            while (newTrimmedLines.length > 0 && newTrimmedLines[newTrimmedLines.length - 1].trim() === "") {
              newTrimmedLines.pop();
            }
            const oldContent = oldTrimmedLines.join("\n");
            const newContent2 = newTrimmedLines.join("\n");
            if (oldContent !== newContent2) {
              console.debug(`Memos Sync: [merge] UPDATING memo uid=${block.uid}`);
              console.debug(`Memos Sync: [merge]   OLD: "${oldContent.substring(0, 100)}"`);
              console.debug(`Memos Sync: [merge]   NEW: "${newContent2.substring(0, 100)}"`);
            } else {
              console.debug(`Memos Sync: [merge] memo uid=${block.uid} unchanged`);
            }
            mergedLines.push(...updated.lines);
          }
        } else {
          mergedLines.push(...block.lines);
        }
      }
      for (const uid of appendAtEnd) {
        const newBlock = newMemoMap.get(uid);
        if (newBlock)
          mergedLines.push(...newBlock.lines);
      }
      while (mergedLines.length > 0 && mergedLines[mergedLines.length - 1].trim() === "") {
        mergedLines.pop();
      }
      const newContent = [
        ...before,
        heading,
        "",
        ...mergedLines,
        "",
        ...after
      ].join("\n").replace(/\n{3,}/g, "\n\n");
      return newContent;
    }
  }
  if (!existingContent.trim()) {
    return memosSection;
  }
  if (settings.insertPosition === "top") {
    return memosSection + "\n" + existingContent;
  } else {
    const trimmed = existingContent.replace(/\n+$/, "");
    return trimmed + "\n\n" + memosSection;
  }
}
function escapeRegExp(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// src/main.ts
var MemosSyncPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.memosApi = new MemosApi(DEFAULT_SETTINGS);
    this.lastSyncTime = "";
    this.syncInterval = null;
    this.startupTimeout = null;
    this.fileOpenRegistered = false;
    this.recentlySynced = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.memosApi = new MemosApi(this.settings);
    this.addRibbonIcon("refresh-cw", "Diary Memos Sync", () => {
      void this.syncMemos();
    });
    this.addCommand({
      id: "sync-memos-now",
      name: "Sync Memos Now",
      callback: () => {
        void this.syncMemos();
      }
    });
    this.addCommand({
      id: "toggle-auto-sync",
      name: "Toggle Auto Sync",
      callback: () => {
        this.settings.autoSync = !this.settings.autoSync;
        void this.saveSettings();
        this.resetAutoSync();
        new import_obsidian3.Notice(
          `Memos auto-sync ${this.settings.autoSync ? "enabled" : "disabled"}`
        );
      }
    });
    this.addSettingTab(new MemosSyncSettingTab(this.app, this));
    this.resetAutoSync();
    this.setupStartupSync();
    this.app.workspace.onLayoutReady(() => {
      this.setupFileOpenSync();
    });
  }
  onunload() {
    this.clearAutoSync();
    this.clearStartupSync();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.memosApi.updateSettings(this.settings);
  }
  /**
   * Main sync logic — syncs today + past N lookback days
   */
  async syncMemos() {
    if (!this.settings.memosServerUrl) {
      new import_obsidian3.Notice("\u26A0\uFE0F Please configure Memos server URL in settings");
      return;
    }
    if (!this.settings.memosAccessToken) {
      new import_obsidian3.Notice("\u26A0\uFE0F Please configure Memos access token in settings");
      return;
    }
    try {
      const lookbackDays = this.settings.syncLookbackDays || 0;
      let totalSynced = 0;
      let daysUpdated = 0;
      const datesToSync = [];
      for (let i = 0; i <= lookbackDays; i++) {
        const d = new Date();
        d.setDate(d.getDate() - i);
        const dateStr = formatDate(d, "YYYY-MM-DD");
        datesToSync.push({ dateStr, date: new Date(d) });
      }
      for (const { dateStr, date } of datesToSync) {
        const memos = await this.memosApi.fetchMemosByDate(dateStr);
        console.debug(`Memos Sync: [syncMemos] Date ${dateStr}: fetched ${memos.length} memo(s)`);
        for (const m of memos) {
          console.debug(`Memos Sync: [syncMemos]   uid=${m.uid}, updateTime=${m.updateTime}, content="${m.content.substring(0, 50)}"`);
        }
        if (memos.length === 0) {
          continue;
        }
        const memosSection = buildMemosSection(memos, this.settings);
        const notePath = getDailyNotePath(date, this.settings);
        let noteContent = "";
        const existingFile = this.app.vault.getAbstractFileByPath(notePath);
        if (existingFile && existingFile instanceof import_obsidian3.TFile) {
          noteContent = await this.app.vault.read(existingFile);
        } else {
          await this.ensureFolderExists(notePath);
        }
        const updatedContent = mergeMemosIntoNote(
          noteContent,
          memosSection,
          this.settings
        );
        if (updatedContent !== noteContent) {
          console.debug(`Memos Sync: [syncMemos] Content changed for ${dateStr}, writing file.`);
          if (existingFile && existingFile instanceof import_obsidian3.TFile) {
            await this.app.vault.modify(existingFile, updatedContent);
          } else {
            await this.app.vault.create(notePath, updatedContent);
          }
          daysUpdated++;
        } else {
          console.debug(`Memos Sync: [syncMemos] Content UNCHANGED for ${dateStr}, skipping write.`);
        }
        totalSynced += memos.length;
      }
      this.updateLastSyncTime();
      console.debug(
        `Memos Sync: Synced ${totalSynced} memo(s) across ${daysUpdated} day(s)`
      );
    } catch (error) {
      console.error("Memos Sync Error:", error);
      new import_obsidian3.Notice(`\u274C Sync failed: ${error.message}`, 8e3);
    }
  }
  /**
   * Ensure the folder for the note exists
   */
  async ensureFolderExists(filePath) {
    const parts = filePath.split("/");
    parts.pop();
    if (parts.length === 0)
      return;
    let currentPath = "";
    for (const part of parts) {
      currentPath = currentPath ? `${currentPath}/${part}` : part;
      const existing = this.app.vault.getAbstractFileByPath(currentPath);
      if (!existing) {
        await this.app.vault.createFolder(currentPath);
      }
    }
  }
  /**
   * Update the last sync timestamp
   */
  updateLastSyncTime() {
    this.lastSyncTime = formatDate(new Date(), "YYYY-MM-DD HH:mm:ss");
  }
  /**
   * Reset auto-sync interval
   */
  resetAutoSync() {
    this.clearAutoSync();
    if (this.settings.autoSync && this.settings.syncIntervalMinutes > 0) {
      const intervalMs = this.settings.syncIntervalMinutes * 60 * 1e3;
      this.syncInterval = window.setInterval(() => {
        console.debug("Memos Sync: Auto-sync triggered");
        void this.syncMemos();
      }, intervalMs);
      this.registerInterval(this.syncInterval);
    }
  }
  /**
   * Clear auto-sync interval
   */
  clearAutoSync() {
    if (this.syncInterval !== null) {
      window.clearInterval(this.syncInterval);
      this.syncInterval = null;
    }
  }
  /**
   * Setup sync on startup with configured delay
   */
  setupStartupSync() {
    this.clearStartupSync();
    const delaySetting = this.settings.syncOnStartup;
    if (delaySetting === "off")
      return;
    const delaySeconds = parseInt(delaySetting, 10);
    if (isNaN(delaySeconds) || delaySeconds < 1)
      return;
    this.startupTimeout = window.setTimeout(() => {
      console.debug(`Memos Sync: Startup sync triggered after ${delaySeconds}s`);
      void this.syncMemos();
    }, delaySeconds * 1e3);
    this.registerInterval(this.startupTimeout);
  }
  /**
   * Clear startup sync timeout
   */
  clearStartupSync() {
    if (this.startupTimeout !== null) {
      window.clearTimeout(this.startupTimeout);
      this.startupTimeout = null;
    }
  }
  /**
   * Setup file-open sync listener (registered once, checks setting inside callback)
   */
  setupFileOpenSync() {
    if (this.fileOpenRegistered)
      return;
    this.fileOpenRegistered = true;
    const DEBOUNCE_MS = 1e4;
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        var _a;
        console.debug(`Memos Sync: [file-open] event fired, file=${(_a = file == null ? void 0 : file.path) != null ? _a : "null"}, syncOnFileOpen=${this.settings.syncOnFileOpen}`);
        if (!this.settings.syncOnFileOpen)
          return;
        if (!file || !(file instanceof import_obsidian3.TFile))
          return;
        if (file.extension !== "md")
          return;
        const dateStr = this.extractDateFromDailyNote(file);
        if (!dateStr) {
          return;
        }
        const lookbackDays = this.settings.syncLookbackDays || 0;
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const fileDate = new Date(dateStr + "T00:00:00");
        const diffDays = Math.floor((today.getTime() - fileDate.getTime()) / (1e3 * 60 * 60 * 24));
        if (diffDays < 0 || diffDays > lookbackDays) {
          console.debug(`Memos Sync: [file-open] Date ${dateStr} is outside lookback range (${diffDays} days ago, max ${lookbackDays}), skipping.`);
          return;
        }
        const lastSync = this.recentlySynced.get(dateStr);
        if (lastSync && Date.now() - lastSync < DEBOUNCE_MS) {
          console.debug(`Memos Sync: [file-open] Date ${dateStr} was recently synced, debouncing.`);
          return;
        }
        this.recentlySynced.set(dateStr, Date.now());
        console.debug(`Memos Sync: [file-open] Sync triggered for ${dateStr} (file: ${file.path})`);
        void this.syncSingleDate(dateStr, fileDate);
      })
    );
    console.debug("Memos Sync: File-open sync listener registered.");
  }
  /**
   * Called from settings toggle — no need to re-register, just log the change
   */
  resetFileOpenSync() {
    this.setupFileOpenSync();
    console.debug(`Memos Sync: syncOnFileOpen is now ${this.settings.syncOnFileOpen ? "enabled" : "disabled"}`);
  }
  /**
   * Extract date string from a daily note file path.
   * Uses the configured fileNameFormat to reverse-parse the date from the file name.
   * Returns YYYY-MM-DD string if the file matches daily note pattern, null otherwise.
   */
  extractDateFromDailyNote(file) {
    const folder = this.settings.dailyNotesFolder.replace(/^\/*|\/*$/g, "");
    const filePath = file.path;
    const fmt = this.settings.fileNameFormat || "YYYY-MM-DD";
    console.debug(`Memos Sync: [extractDate] filePath="${filePath}", folder="${folder}", fileNameFormat="${fmt}"`);
    if (folder) {
      const normalizedPath = filePath.toLowerCase();
      const normalizedFolder = folder.toLowerCase();
      if (!normalizedPath.startsWith(normalizedFolder + "/")) {
        console.debug(`Memos Sync: [extractDate] Path does not start with folder "${folder}/", skipping.`);
        return null;
      }
    }
    const relativePath = folder ? filePath.slice(folder.length + 1) : filePath;
    const pathWithoutExt = relativePath.replace(/\.md$/i, "");
    console.debug(`Memos Sync: [extractDate] pathWithoutExt="${pathWithoutExt}"`);
    const dateStr = this.parseDateFromFormat(pathWithoutExt, fmt);
    if (dateStr) {
      console.debug(`Memos Sync: [extractDate] Parsed date ${dateStr} using format "${fmt}"`);
      return dateStr;
    }
    const dashMatch = filePath.match(/(\d{4})-(\d{2})-(\d{2})/);
    if (dashMatch) {
      const d = `${dashMatch[1]}-${dashMatch[2]}-${dashMatch[3]}`;
      if (!isNaN(new Date(d + "T00:00:00").getTime())) {
        console.debug(`Memos Sync: [extractDate] Fallback matched YYYY-MM-DD: ${d}`);
        return d;
      }
    }
    const compactMatch = filePath.match(/(\d{4})(\d{2})(\d{2})/);
    if (compactMatch) {
      const d = `${compactMatch[1]}-${compactMatch[2]}-${compactMatch[3]}`;
      if (!isNaN(new Date(d + "T00:00:00").getTime())) {
        console.debug(`Memos Sync: [extractDate] Fallback matched YYYYMMDD: ${d}`);
        return d;
      }
    }
    console.debug(`Memos Sync: [extractDate] No date found in "${filePath}"`);
    return null;
  }
  /**
   * Parse a date string from a formatted path using the user's fileNameFormat.
   * E.g., format="YYYYMMDD", input="20260225" → "2026-02-25"
   * E.g., format="YYYY-MM-DD", input="2026-02-25" → "2026-02-25"
   * E.g., format="YYYY/MM/YYYY-MM-DD", input="2026/02/2026-02-25" → "2026-02-25"
   */
  parseDateFromFormat(input, format) {
    let regexStr = format.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    regexStr = regexStr.replace(/YYYY/g, "(\\d{4})");
    regexStr = regexStr.replace(/MM/g, "(\\d{2})");
    regexStr = regexStr.replace(/DD/g, "(\\d{2})");
    const tokenPositions = [];
    let searchFmt = format;
    const tokens = ["YYYY", "MM", "DD"];
    for (const token of tokens) {
      let pos = searchFmt.indexOf(token);
      while (pos !== -1) {
        tokenPositions.push({ token, index: pos });
        searchFmt = searchFmt.substring(0, pos) + "X".repeat(token.length) + searchFmt.substring(pos + token.length);
        pos = searchFmt.indexOf(token);
      }
    }
    tokenPositions.sort((a, b) => a.index - b.index);
    const regex = new RegExp("^" + regexStr + "$");
    const match = input.match(regex);
    if (!match) {
      console.debug(`Memos Sync: [parseDateFromFormat] No match. input="${input}", regex=${regex}`);
      return null;
    }
    let year = "", month = "", day = "";
    for (let i = 0; i < tokenPositions.length; i++) {
      const val = match[i + 1];
      switch (tokenPositions[i].token) {
        case "YYYY":
          year = val;
          break;
        case "MM":
          month = val;
          break;
        case "DD":
          day = val;
          break;
      }
    }
    if (!year || !month || !day) {
      console.debug(`Memos Sync: [parseDateFromFormat] Missing date parts: year=${year}, month=${month}, day=${day}`);
      return null;
    }
    const dateStr = `${year}-${month}-${day}`;
    const parsed = new Date(dateStr + "T00:00:00");
    if (isNaN(parsed.getTime())) {
      console.debug(`Memos Sync: [parseDateFromFormat] Invalid date: ${dateStr}`);
      return null;
    }
    return dateStr;
  }
  /**
   * Sync memos for a single date
   */
  async syncSingleDate(dateStr, date) {
    if (!this.settings.memosServerUrl || !this.settings.memosAccessToken) {
      return;
    }
    try {
      const memos = await this.memosApi.fetchMemosByDate(dateStr);
      if (memos.length === 0)
        return;
      const memosSection = buildMemosSection(memos, this.settings);
      const notePath = getDailyNotePath(date, this.settings);
      let noteContent = "";
      const existingFile = this.app.vault.getAbstractFileByPath(notePath);
      if (existingFile && existingFile instanceof import_obsidian3.TFile) {
        noteContent = await this.app.vault.read(existingFile);
      } else {
        await this.ensureFolderExists(notePath);
      }
      const updatedContent = mergeMemosIntoNote(
        noteContent,
        memosSection,
        this.settings
      );
      if (updatedContent !== noteContent) {
        if (existingFile && existingFile instanceof import_obsidian3.TFile) {
          await this.app.vault.modify(existingFile, updatedContent);
        } else {
          await this.app.vault.create(notePath, updatedContent);
        }
        console.debug(`Memos Sync: Updated memos for ${dateStr}`);
      }
      this.updateLastSyncTime();
    } catch (error) {
      console.error(`Memos Sync Error (${dateStr}):`, error);
      new import_obsidian3.Notice(`\u274C Sync failed for ${dateStr}: ${error.message}`, 8e3);
    }
  }
};
